name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  MAPBOX_TOKEN: ''

jobs:
  run-build:
    name: Build Assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: cd web-canada && npm i
      - run: cd web-canada && npm run build
      - name: Sync to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER_CANADA }}
          username: ${{ secrets.FTP_USER_CANADA }}
          password: ${{ secrets.FTP_PW_CANADA }}
          local-dir: "./web-canada/dist/"