name: PR Builds Aaron Czichon

on:
  pull_request:
    branches:
      - main

jobs:
  run-build:
    name: Build Assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: cd personal && npm i
      - run: cd personal && npm run build