name: PR Builds Aaron Czichon

on:
  pull_request:
    branches:
      - main

jobs:
  check-links:
    name: Check Links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v1
        with:
          args: --base ./site/src/content --verbose --no-progress './**/*.md'
          # Use json as output format (instead of markdown)
          format: json
  run-build:
    name: Build Assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: cd site && npm i
      - run: cd site && npm run build