name: PR Builds Aaron Czichon

on:
  pull_request:
    branches:
      - main

jobs:
  check-links:
    name: Check Links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v1
        with:
          args: --base ./site/src/content --verbose --no-progress './**/*.md' --max-concurrency 10 --exclude cloudflarestream\.com
          # Use json as output format (instead of markdown)
          #format: json
      - uses: actions/upload-artifact@v4
        with:
          name: link-report.md
          path: ./lychee/out.md
  run-build:
    name: Build Assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: cd site && npm i
      - run: cd site && npm run build
  bundle-directus:
    name: Build Directus Extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: cd comment-submit && npm i
      - run: cd comment-submit && npm run build
      # Zip the extension folder only (comment-submit) from root folder starting
      - uses: actions/upload-artifact@v4
        with:
          name: directus-extension-comment-submit.zip
          path: ./comment-submit
